spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/demo
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: stoneberg
    password: new1234@

    hikari:
      connection-timeout: 60000
      minimum-idle: 3
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 500
      hibernate.jdbc.lob.non_contextual_creation: true

#  datasource:
#    url: jdbc:p6spy:h2:mem:testdb
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        default_batch_fetch_size: 500
#        jdbc.lob.non_contextual_creation: true
#       show_sql: true
#       format_sql: true
#       use_sql_comments: true


#logging:
#  level:
#    org.hibernate.type.descriptor.sql: trace
